version: '2'

services:
    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=netbox
            - POSTGRES_PASSWORD=netbox

    netbox:
        image: pitkley/netbox
        environment:
            - "ALLOWED_HOSTS=netbox.dev localhost"
            - "DB_HOST=db"
            - "DB_NAME=netbox"
            - "DB_USER=netbox"
            - "DB_PASSWORD=netbox"
            - "SECRET_KEY=" # change me

